import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,CheckCircle2,ChevronRight,ExternalLink,ShieldCheck,AlertTriangle,RotateCcw} from 'lucide-react';
import './styles.css';

const API='https://sarkar-lens.onrender.com';
const statusLabels={not_started:'Not started',in_progress:'In progress',completed:'Completed',not_applicable:'Not applicable'};

function App(){
 const [screen,setScreen]=useState('home'); const [input,setInput]=useState(''); const [facts,setFacts]=useState(null); const [services,setServices]=useState([]); const [sessionId,setSessionId]=useState(null); const [selected,setSelected]=useState(null); const [progress,setProgressState]=useState({}); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 async function build(){setLoading(true);setError('');try{const r=await fetch(`${API}/api/checklist`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input})});const d=await r.json();if(!r.ok)throw new Error(d.error);setFacts(d.facts);setServices(d.services);setSessionId(d.sessionId);setScreen('confirm');}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function goChecklist(){setLoading(true);setError('');try{const r=await fetch(`${API}/api/checklist`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({facts})});const d=await r.json();if(!r.ok)throw new Error(d.error);setFacts(d.facts);setServices(d.services);setSessionId(d.sessionId);setProgressState({});setScreen('checklist')}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function setStatus(id,status){setProgressState(p=>({...p,[id]:status}));await fetch(`${API}/api/progress`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,serviceId:id,status})});}
 const completed=services.filter(s=>progress[s.id]==='completed').length; const attention=services.length-completed;
 return <div className="app"><header><div className="brand" onClick={()=>setScreen('home')}>Sarkar<span>Lens</span></div><div className="nav">{sessionId&&<button className={screen==='checklist'?'active':''} onClick={()=>setScreen('checklist')}>Checklist</button>}{sessionId&&<button className={screen==='dashboard'?'active':''} onClick={()=>setScreen('dashboard')}>Progress</button>}</div></header>
 {screen==='home'&&<main className="hero"><div className="eyebrow">CITIZEN TASK ORGANIZER</div><h1>Tell us what changed.<br/><em>We'll tell you what the government needs from you.</em></h1><p className="lead">Describe a life event in plain language. Sarkar Lens turns verified government-service records into a focused action list.</p><div className="inputCard"><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="I'm moving from Noida to Bengaluru. I'm renting and I don't own a car."/><div className="inputBottom"><span>Example input is interpreted by a structured parser.</span><button onClick={build} disabled={!input.trim()||loading}>{loading?'Building…':'Build my checklist'} <ArrowRight size={18}/></button></div></div>{error&&<div className="error"><AlertTriangle size={18}/>{error}</div>}<div className="trust"><ShieldCheck size={18}/> Government procedures come from the application's service knowledge base. The AI does not generate official URLs or requirements.</div></main>}
 {screen==='confirm'&&<main className="page"><div className="eyebrow">STEP 1 OF 3</div><h2>Confirm what we understood</h2><p className="muted">Only facts extracted from your description are used by the rules engine.</p><div className="facts">{[['Life event',facts?.life_event],['Current location',facts?.origin||'Not provided'],['New location',facts?.destination||'Not provided'],['Housing',facts?.housing||'Not provided'],['Owns vehicle',facts?.owns_vehicle===null?'Not provided':facts?.owns_vehicle?'Yes':'No'],['Voter registered',facts?.voter_registered===null?'Need to ask':facts?.voter_registered?'Yes':'No']].map(([k,v])=><div className="fact" key={k}><span>{k}</span><strong>{String(v).replaceAll('_',' ')}</strong></div>)}</div><div className="question"><div><strong>One relevant question</strong><p>Are you currently registered to vote?</p></div><div className="options"><button className={facts?.voter_registered===true?'selected':''} onClick={()=>setFacts({...facts,voter_registered:true})}>Yes</button><button className={facts?.voter_registered===false?'selected':''} onClick={()=>setFacts({...facts,voter_registered:false})}>No</button><button className={facts?.voter_registered===null?'selected':''} onClick={()=>setFacts({...facts,voter_registered:null})}>Skip</button></div></div><button className="primary" onClick={goChecklist} disabled={loading}>{loading?'Building…':'Generate personalized checklist'} <ArrowRight size={18}/></button></main>}
 {screen==='checklist'&&<main className="page"><div className="topline"><div><div className="eyebrow">STEP 2 OF 3</div><h2>Your government checklist</h2><p className="muted">{services.length} relevant service{services.length!==1?'s':''} matched from verified/placeholder records.</p></div><div className="summary"><b>{completed}/{services.length}</b><span>completed</span></div></div><div className="progress"><span style={{width:`${services.length?completed/services.length*100:0}%`}}/></div>{services.length===0?<div className="empty">No service can be safely recommended from the current knowledge base. The application will not invent one.</div>:<div className="cards">{services.map((s,i)=><ServiceCard key={s.id} service={s} index={i} status={progress[s.id]||'not_started'} onStatus={setStatus} onOpen={()=>{setSelected(s);setScreen('detail')}}/> )}</div>}<button className="secondary" onClick={()=>setScreen('dashboard')}>Open progress dashboard <ChevronRight size={17}/></button></main>}
 {screen==='detail'&&selected&&<main className="page"><button className="back" onClick={()=>setScreen('checklist')}>← Back to checklist</button><div className="detailHead"><div><div className="eyebrow">SERVICE RECORD</div><h2>{selected.name}</h2><p className="muted">{selected.description}</p></div><span className={`badge ${selected.verification_status}`}>{selected.verification_status==='verified'?'Verified source':'Placeholder / unverified'}</span></div><div className="detailGrid"><section><h3>Why this applies</h3><p>{selected.reason||'This service matches the selected facts.'}</p><h3>Who it applies to</h3><p>{selected.conditions.map((c,i)=><span key={i} className="chip">{c.fact.replaceAll('_',' ')}</span>)}</p><h3>Documents</h3><ul>{selected.documents.map(x=><li key={x}>{x}</li>)}</ul></section><section><h3>Process</h3><ol>{selected.steps.map(x=><li key={x}>{x}</li>)}</ol><div className="authority"><span>Authority</span><b>{selected.authority}</b><span>Complexity</span><b>{selected.complexity}</b><span>Last verified</span><b>{selected.last_verified||'Not verified'}</b></div>{selected.official_url?<a className="primary link" href={selected.official_url} target="_blank" rel="noreferrer">Go to official service <ExternalLink size={17}/></a>:<div className="warning"><AlertTriangle size={17}/> No official URL stored. This service is intentionally blocked from linking.</div>}</section></div></main>}
 {screen==='dashboard'&&<main className="page"><div className="eyebrow">STEP 3 OF 3</div><h2>Progress dashboard</h2><div className="dashboardStats"><div><b>{services.length}</b><span>Total tasks</span></div><div><b>{completed}</b><span>Completed</span></div><div><b>{attention}</b><span>Need attention</span></div></div><div className="dashboardList">{services.map(s=><div className="dashRow" key={s.id}><div><b>{s.name}</b><span>{statusLabels[progress[s.id]||'not_started']}</span></div><select value={progress[s.id]||'not_started'} onChange={e=>setStatus(s.id,e.target.value)}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>)}</div><div className="dependency"><div><h3>Dependency graph</h3><p className="muted">Only relationships explicitly stored in the knowledge base are shown.</p></div><DependencyGraph services={services}/></div><button className="secondary" onClick={()=>{setScreen('home');setSessionId(null);setServices([]);setProgressState({});setInput('')}}><RotateCcw size={17}/> Start another situation</button></main>}
 </div>
}
function ServiceCard({service,index,status,onStatus,onOpen}){return <article className="card"><div className="cardTop"><div className="number">{String(index+1).padStart(2,'0')}</div><div><div className="cardTitle">{service.name}</div><span className={`status ${status}`}>{statusLabels[status]}</span></div><div className="cardAction"><button onClick={onOpen}>View process <ChevronRight size={16}/></button></div></div><p className="why"><b>Why:</b> {service.reason||service.description}</p><div className="docLine"><b>Documents:</b> {service.documents.slice(0,3).join(' · ')}</div><div className="cardBottom"><select value={status} onChange={e=>onStatus(service.id,e.target.value)}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{service.verification_status==='verified'?<span className="verified"><CheckCircle2 size={15}/> Verified source</span>:<span className="placeholder">Placeholder data</span>}</div></article>}
function DependencyGraph({services}){const links=services.flatMap(s=>s.dependencies.map(d=>({from:d,to:s.id})));return <div className="graph">{links.length===0?<div className="graphEmpty">No dependencies are stored for this checklist.</div>:links.map(l=><div key={l.from+l.to} className="edge"><span>{services.find(s=>s.id===l.from)?.name||l.from}</span><ArrowRight size={16}/><span>{services.find(s=>s.id===l.to)?.name||l.to}</span></div>)}</div>}
createRoot(document.getElementById('root')).render(<App/>);
